server:
  port: 9010
spring:
  application:
    name: tensquare-friend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.12.98:3306/tensquare_friend?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    host: 192.168.12.98
jwt:
  config:
    key: codewj
eureka:
  client:
    service-url:
      defaultZone: http://192.168.12.98:6868/eureka/
  instance:
    prefer-ip-address: true
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000