server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.12.98
aliyun:
  sms:
    accessKeyId: LTAIxo9ZQy1tSHYL
    accessKeySecret: IawJXWPqlMvG69lzCcEOBoyvGvwE5G
    template_code: SMS_94700095
    sign_name: codewj